# Generated by Django 4.2.5 on 2023-09-22 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_world', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Description',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='bookstore',
            name='poster',
        ),
        migrations.AddField(
            model_name='book',
            name='poster',
            field=models.ImageField(blank=True, upload_to='book_cover/'),
        ),
        migrations.AddField(
            model_name='bookstore',
            name='book_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book_world.book'),
        ),
    ]
