# Generated by Django 4.2.5 on 2023-09-25 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_world', '0002_rename_description_book_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAdditionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pages', models.IntegerField()),
                ('author', models.CharField(default='Unknown', max_length=30)),
                ('publisher', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='ALL', max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='BookCollection',
        ),
        migrations.RenameField(
            model_name='bookstore',
            old_name='book',
            new_name='book_storage',
        ),
        migrations.RemoveField(
            model_name='bookstore',
            name='book_info',
        ),
        migrations.AddField(
            model_name='book',
            name='storage_path',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book_world.bookstore'),
        ),
        migrations.AddField(
            model_name='bookadditionalinfo',
            name='book',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_info', to='book_world.book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_world.category'),
        ),
    ]
